#!/bin/sh

case "$1" in
start)
	/sbin/modprobe phy-rockchip-inno-usb2
	/sbin/modprobe usb_f_fs
	/sbin/modprobe dwc2

        ;;
stop)
        ;;
*)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
