## 1M
TARGET=$1

# remove udev hwdb
rm -rfv $TARGET/etc/udev/hwdb.d/*.hwdb
# remove sample
rm -rfv $TARGET/usr/bin/rk_mpi_*

rm -rfv $TARGET/usr/sbin/v4l2-dbg
rm -rfv $TARGET/usr/sbin/irqbalance
#rm -rfv $TARGET/usr/lib/libpcre.so.1.2.13
#rm -rfv $TARGET/usr/lib/udev/fido_id
#rm -rfv $TARGET/usr/lib/libnl-nf-3.so.200.26.0
#rm -rfv $TARGET/usr/lib/udev/ata_id
#rm -rfv $TARGET/usr/lib/udev/collect
#rm -rfv $TARGET/usr/bin/ir-keytable
#rm -rfv $TARGET/usr/bin/lowntfs-3g
#rm -rfv $TARGET/usr/sbin/tune2fs
#rm -rfv $TARGET/usr/lib/udev/dmi_memory_id
#rm -rfv $TARGET/usr/lib/udev/scsi_id
#rm -rfv $TARGET/usr/lib/libatopology.so.2.0.0
#rm -rfv $TARGET/usr/sbin/alsactl
#rm -rfv $TARGET/usr/lib/librkaudio_common.so
#rm -rfv $TARGET/usr/lib/udev/cdrom_id
#rm -rfv $TARGET/usr/lib/ossl-modules/legacy.so
#rm -rfv $TARGET/usr/sbin/mke2fs
#rm -rfv $TARGET/usr/sbin/wpa_cli
#rm -rfv $TARGET/usr/lib/libnl-3.so.200.26.0
#rm -rfv $TARGET/usr/lib/libevent_extra-2.1.so.7.0.1
#rm -rfv $TARGET/usr/lib/librkaudio.so
#rm -rfv $TARGET/usr/lib/libv4lconvert.so.0.0.0
rm -rfv $TARGET/usr/bin/ntfs-3g
#rm -rfv $TARGET/usr/lib/libudev.so.1.6.3
#rm -rfv $TARGET/usr/lib/libgraphic_lsf.so
#rm -rfv $TARGET/usr/lib/libcgicc.so.3.2.10
#rm -rfv $TARGET/usr/bin/cec-follower
#rm -rfv $TARGET/info/config-6.1
#rm -rfv $TARGET/usr/lib/ld-linux-aarch64.so.1
rm -rfv $TARGET/usr/lib/librkrawstream.so
#rm -rfv $TARGET/usr/lib/libpng16.so.16.41.0
#rm -rfv $TARGET/usr/lib/libevent_core-2.1.so.7.0.1
#rm -rfv $TARGET/usr/lib/librga.so.2.1.0
#rm -rfv $TARGET/usr/lib/libjpeg.so
#rm -rfv $TARGET/usr/lib/libfuse3.so.3.16.2
#rm -rfv $TARGET/usr/lib/libturbojpeg.so
#rm -rfv $TARGET/usr/bin/cec-compliance
#rm -rfv $TARGET/usr/lib/librkaudio_vqe.so
#rm -rfv $TARGET/usr/lib/libntfs-3g.so.89.0.0
#rm -rfv $TARGET/usr/bin/cec-ctl
#rm -rfv $TARGET/usr/lib/libdvbv5.so.0.0.0
#rm -rfv $TARGET/usr/sbin/udevd
#rm -rfv $TARGET/usr/sbin/e2fsck
#rm -rfv $TARGET/usr/lib/libncurses.so.6.4
#rm -rfv $TARGET/usr/lib/libpcre2-8.so.0.11.2
#rm -rfv $TARGET/usr/lib/libevent-2.1.so.7.0.1
#rm -rfv $TARGET/usr/bin/udevadm
#rm -rfv $TARGET/usr/lib/libreadline.so.8.2
#rm -rfv $TARGET/usr/bin/rkaiq_tool_server
#rm -rfv $TARGET/usr/lib/libblkid.so.1.1.0
#rm -rfv $TARGET/usr/lib/libparted.so.2.0.5
#rm -rfv $TARGET/usr/lib/libgobject-2.0.so.0.7600.1
#rm -rfv $TARGET/usr/lib/libext2fs.so.2.4
#rm -rfv $TARGET/usr/bin/input-event-daemon
rm -rfv $TARGET/usr/bin/rknn_server
#rm -rfv $TARGET/usr/lib/libmount.so.1.1.0
rm -rfv $TARGET/usr/bin/v4l2-ctl
rm -rfv $TARGET/usr/lib/libRkSwCac.so
rm -rfv $TARGET/usr/bin/kmsgrab
#rm -rfv $TARGET/usr/lib/libm.so.6
#rm -rfv $TARGET/usr/bin/inotifywait
#rm -rfv $TARGET/usr/lib/libnl-route-3.so.200.26.0
rm -rfv $TARGET/usr/bin/modetest
#rm -rfv $TARGET/usr/lib/librkmuxer.so
#rm -rfv $TARGET/usr/lib/libfreetype.so.6.20.1
rm -rfv $TARGET/usr/bin/v4l2-compliance
#rm -rfv $TARGET/usr/bin/rkipc
rm -rfv $TARGET/etc/iqfiles/ov16880_KYT-11379-V1_default.json
rm -rfv $TARGET/etc/iqfiles/gc05a2_KYT-11210-V2_default.json
#rm -rfv $TARGET/usr/bin/busybox
#rm -rfv $TARGET/usr/sbin/ntpd
rm -rfv $TARGET/etc/iqfiles/imx464_CMK-OT1980-PX1_SHG102.json
#rm -rfv $TARGET/usr/lib/librkdemuxer.so
#rm -rfv $TARGET/usr/lib/libssl.so.3
#rm -rfv $TARGET/usr/lib/liblvgl.so
#rm -rfv $TARGET/usr/bin/bash

# more 1M
rm -rfv $TARGET/etc/iqfiles/sc4336_OT01_40IRC_F16.json
#rm -rfv $TARGET/usr/lib/libasound.so.2.0.0
rm -rfv $TARGET/usr/sbin/wpa_supplicant
rm -rfv $TARGET/etc/iqfiles/ox03c10_default_default.json
#rm -rfv $TARGET/usr/lib/librkaiq.so
### debug
#rm -rfv $TARGET/usr/share/PuHuiTi.ttf
rm -rfv $TARGET/etc/iqfiles/os04a10_CMK-OT1607-FV1_M12-40IRC-4MP-F16.json
rm -rfv $TARGET/etc/iqfiles/s5k4h5yb_G1-T-B-s5k_XA-0806B.json
#rm -rfv $TARGET/usr/lib/libglib-2.0.so.0.7600.1
#rm -rfv $TARGET/usr/sbin/irqbalance
#rm -rfv $TARGET/usr/lib/libc.so.6
#rm -rfv $TARGET/etc/iqfiles/imx386_CMK-OT2022-PX1_IR0147-50IRC-8M-F20.json
rm -rfv $TARGET/etc/iqfiles/imx415_CMK-OT2022-PX1_IR0147-50IRC-8M-F20.json
rm -rfv $TARGET/usr/lib/libgio-2.0.so.0.7600.1
#rm -rfv $TARGET/usr/lib/librockchip_mpp.so.0
#rm -rfv $TARGET/usr/lib/libstdc++.so.6.0.30
#rm -rfv $TARGET/usr/lib/librockit.so
#rm -rfv $TARGET/usr/bin/adbd
rm -rfv $TARGET/info/System.map-6.1
rm -rfv $TARGET/usr/share/model
#rm -rfv $TARGET/usr/lib/libcrypto.so.3
rm -rfv $TARGET/usr/bin/rknn_common_test
rm -rfv $TARGET/usr/lib/librknnrt.so
#rm -rfv $TARGET/usr/lib/libRkEis.so
rm -rfv $TARGET/etc/udev/hwdb.bin
